import type { Project } from '../types'

export const projects: Project[] = [
  {
    id: 'neural-synthesis-interface',
    year: 2024,
    category: 'Research',
    title: 'Neural Synthesis Interface',
    description:
      'An AI-powered design assistant that synthesizes user research insights into actionable design recommendations. Built with React and a custom NLP pipeline, reducing ideation time by 40%.',
    tags: ['Research', 'AI/ML'],
    duration: '6 months',
    team: 'Solo',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAhGDnsigYMORq0yDd4-G3St2O8n9NLCUtUteVa_8XPa0WvmZjhsmIxsTDeCs7J4ieb1SY22LEV88HO4Gef5X2qS8mbPo2BPg9CSk4-LD_u6b2FX6y2eYFyApHvYxFjiQ1U6Y9To8hmydzr9dMrhZwZlfmAyr1MT1mR-vRzN_WIV8V6OyuPlTa2SBvNehdjzAFAIz7cPP64QhVj0OzBgvHCvvlhh0Bn693_vI5OKB_NQWoNr65YEyKCiQyHHZaSJ2VTpCyWeDbWB9Bc',
    caseStudyUrl: '#',
    accentColor: 'primary',
    detail: {
      role: 'Lead Architect',
      mission: [
        'Neural Synthesis Patterns was conceived as the bridge between theoretical generative art and the physical constraints of autonomous fabrication. We focused on the transition from latent space mathematics to real-world robotic execution, ensuring that every crystalline vertex generated by the neural engine could be physically realized by high-precision six-axis industrial arms.',
        "The challenge lay in translating high-dimensional emotional sensory data into structural load-bearing geometries. By integrating a feedback loop between the generative model and robotic stress-test sensors, we achieved a level of execution where the machine doesn't just print a design, but actively compensates for material variance and gravitational forces in real-time, resulting in hyper-optimized, bio-mimetic spatial structures.",
      ],
      objectives: [
        'Autonomous Fabrication Loops',
        'Emotional Data Mapping',
        'Real-time Structural Correction',
        'BIM Software Integration',
      ],
      techCards: [
        {
          icon: 'memory',
          title: 'Neural Engine',
          description: 'Custom TensorFlow layers designed for high-dimensional latent space manipulation.',
          tags: ['Python', 'TensorFlow', 'PyTorch'],
          variant: 'elevated',
        },
        {
          icon: 'dashboard',
          title: 'Real-time Visualization',
          description: 'A React-based dashboard using Three.js for 60fps rendering of complex vertex shaders.',
          tags: ['React', 'Three.js', 'GLSL'],
          variant: 'elevated',
        },
        {
          icon: 'hub',
          title: 'Distributed Processing',
          description: 'Kubernetes clusters managing synthesis nodes.',
          tags: [],
          variant: 'mini',
        },
        {
          icon: 'database',
          title: 'Data Ingestion',
          description: 'PostgreSQL handling TBs of structural training data.',
          tags: [],
          variant: 'mini',
        },
        {
          icon: 'security',
          title: 'Privacy Layer',
          description: 'Differential privacy on sensitive sensory input.',
          tags: [],
          variant: 'mini',
        },
      ],
      evolution: [
        {
          month: 'Month 01',
          title: 'Concept',
          description:
            'The initial phase involved defining the core thesis of neural-spatial interaction. We conducted extensive feasibility studies to validate the possibility of mapping high-dimensional latent patterns into structural CAD formats.',
          imageUrl:
            'https://lh3.googleusercontent.com/aida-public/AB6AXuAz5IqGMp0lB4410nu82W4_wJJRyXBUP2tF_S_CXfSkmxLRtmYUTaYMCJaJLhUBLUuw0lYiURhUyc49tglLu40qhERf0I7bToCNN-pvpQcWIZQ5Y_Hh7049Zv5rpW8ZCkW4o0bxrD1S0TeBxch4kZt1jPH5af9oRGNyVx9GMG1Ckn0vEucuXSH3UNGCNX0m8M_VzcZmbGG7jfQt-fbzr4fAb89OIZ9CNtNsvkK7-K6UUpOpqhel7Dc6Z4xx_Obm20rY7PgXQfnaHVMR',
          imageAlt:
            'Sketchy, conceptual blueprint of neural networks transitioning into geometric crystal shapes',
        },
        {
          month: 'Month 03',
          title: 'R&D Phase',
          description:
            'Model training was the primary focus, utilizing a custom dataset of 50,000+ structural patterns. We developed the specialized neural engine architecture to handle real-time spatial synthesis with extremely low latency.',
          imageUrl:
            'https://lh3.googleusercontent.com/aida-public/AB6AXuChIl1xes8Zx-zYDSQL-6Th69tPi8K8f46QShyhQIv8iZ43Xu-Iij6czXMNpTxMerIjKsoviHCPOcFw9vblQDp94Wh3hAHAwaSKxv7DL8tN8bPF9EhEwAyWfLl_wJohpJGkFHDycbciqYFLxs57QNHMYcXsZ_BdLSoG3YKlPAaLmgLyWq4eUu0dsAGo3evX8pfnr6_nRWFbqATsNVrc2spHaizgDPSHeUin10MbG-XL8Cme10d1GPM197zBx8FT_QLejWrTrT3rVmIZ',
          imageAlt: 'Glowing neural network nodes with complex data connections in a dark space',
        },
        {
          month: 'Month 05',
          title: 'Prototype',
          description:
            'Our first working interface integrated a real-time feedback loop between digital mesh generation and sensory input. This milestone successfully rendered our first coherent 3D crystalline structure in a high-fidelity simulator.',
          imageUrl:
            'https://lh3.googleusercontent.com/aida-public/AB6AXuBiq4Kv6myMyLw7CEuKMlJG9hM9puTDQkUA-7YxpcEbmuFp8lnC-L437Ep_PfFMKrROvZ4PHgBqbt3MJmtuUHzjWy6A02JcpLVgeY8D2IzjD2TG73UHAzbI_pkk3D081qHv60jJsnwooZRLg1R92btOMZpmhDAyDdRnCt40jIilhEiwlp7VD1wjJHfCxHRlEVc9gOkyvg2aQLk3MBJ9B4Fy6K6SuZC1ojPy91zfM34quDWLOawucErD2KfKdsUlxgwMh7tHvDN_uuel',
          imageAlt: 'A 3D translucent crystalline structure rendered with glowing blue edges',
        },
        {
          month: 'Month 06',
          title: 'V1.0 Launch',
          description:
            'The official public release of the synthesis engine API and web visualizer. This phase marked the full integration with major BIM software and the successful deployment of the first robotic fabrication node.',
          imageUrl:
            'https://lh3.googleusercontent.com/aida-public/AB6AXuB6MKXy0LksQiNQCYS65Ych2WzTPQsmEYwFs0FhMd-d4OKAXn-IiOt3QhqHeVBXzsbtmFpbs_OUXLJ39Lt9cR8zckPBFG2UNQi4nsPvGQH6BxVrvN5kmKDyL8W4NTVJT8ozy8uuTjBqg9D7zJvoFbKXJOHv23CeetHjGvt3meRTu2q2bq1PYkgsvwkyy0mK69RXpeMMbAb7MZb3NTArBA-jLA7AfgRhP9LT6S6T1MqHRJgBu2FLli_ry2VWcxQStYvDXUg3q_lwnJYw',
          imageAlt: 'Close up of a high-tech robotic arm executing a precision movement',
        },
      ],
      metrics: [
        { value: '92%', label: 'Neural Accuracy' },
        { value: '4.2x', label: 'Speed Increase' },
        { value: '12k+', label: 'Generated Models' },
        { value: 'A++', label: 'Efficiency Rating' },
      ],
    },
  },
  {
    id: 'atmosphere-io',
    year: 2024,
    category: 'Design',
    title: 'Atmosphere.IO',
    description:
      'A real-time environmental data visualization app helping communities track local air quality, sound pollution, and green space availability. Featured in 3 school district programs.',
    tags: ['Design', 'Mobile'],
    duration: '4 months',
    team: 'Team of 3',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCC572lYTWfzkN3wxGsyad6nq_Yg-oMjhkAjrjHBgBfR6RvbEgDQ8Vm39vrQbZjoMHql_XVHuSxrVrsoPf35T6A_f0UO03t5bnsHS7BT_6zYCsl2Ce6jjFW2D4xIrd6IgYljeZaY4pM0KIADLcESp1Bo8hUoAU4AGaiNdy2v2HoHsjazacUWQMdk659tbW_puZRUJOx-Tn0ryi-GTQcl0w4VGZwjQ4kikbgr9OcT0GlIxRbKm82eqfezmyYsjhyFUg8yPmXY7Q2CiPH',
    caseStudyUrl: '#',
    accentColor: 'tertiary',
  },
  {
    id: 'lumina-reading-aid',
    year: 2023,
    category: 'Design',
    title: 'Lumina — Reading Aid',
    description:
      'An AI-assisted reading interface designed for students with dyslexia. Won Google Student Developer Challenge Top 10. Features adaptive typography, bionic reading mode, and voice-over integration.',
    tags: ['Design', 'Accessibility'],
    duration: '',
    team: '',
    imageUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCO-l-G6ckidMy2PnnWWSUqm9vBPdQqg4AE1gNj07rLOVHAfkyoShYdtGqkO0PUEtxf8_K6NC93x4vD3gsuReApHsZq5g9juBCPBIA9pO5u99R6DNLezTxGoaJL_7s20HBlxm0B4V9DId5-WfxjWcTJXJ_NM9rNVfv7gW9WyAcc4zEzP7Fxux1glbNRxW-zMtmHW2EsxZXD97zahgT8q3Zuw0PEWHUaQUuO5gzKp43T533fG-F3-a',
    caseStudyUrl: '#',
    accentColor: 'primary',
    award: 'Google SDC Top 10',
  },
  {
    id: 'civic-connect',
    year: 2023,
    category: 'Design',
    title: 'Civic Connect',
    description:
      'An inclusive civic engagement app for first-time voters. Guided onboarding, local representative lookup, and plain-language policy explainers. Won AIGA National HS Design Challenge 1st Place.',
    tags: ['Design', 'Civic Tech'],
    duration: '3 months',
    team: 'Solo',
    imageUrl: null,
    placeholderIcon: 'how_to_vote',
    caseStudyUrl: '#',
    accentColor: 'yellow',
    award: 'AIGA 1st Place · National',
  },
]
